### ISSUE TITLE
rndc reload stopped working after last DSM update

### ISSUE THREAD

**Issue by OderDochNicht** [schmaun/ad-blocker.sh#1]
Since th last DSM update to DSM 6.1.6-15266 rnd reload bring an error:
---------------------------------------
<root@BS58-NAS>~ $:./ad-blocker.sh 
--2018-03-31 13:29:36--  http://pgl.yoyo.org/as/serverlist.php?hostformat=bindconfig&showintro=0&mimetype=plaintext
Resolving pgl.yoyo.org... 213.230.210.230
Connecting to pgl.yoyo.org|213.230.210.230|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: 'serverlist.php?hostformat=bindconfig&showintro=0&mimetype=plaintext'

    [ <=>                                                                                                                                                                                                 ] 199,375     1.11MB/s   in 0.2s   

2018-03-31 13:29:36 (1.11 MB/s) - 'serverlist.php?hostformat=bindconfig&showintro=0&mimetype=plaintext' saved [199375]

Eigene blacklist angefügt 
rndc: neither //etc/rndc.conf nor /var/packages/DNSServer/target/named/rndc.key was found
------------------------------------------
Also a "rndc reload" from root brings this:
------------------------------------------
 <root@BS58-NAS>~ $:rndc reload
rndc: connection to remote host closed
This may indicate that
* the remote server is using an older version of the command protocol,
* this host is not authorized to connect,
* the clocks are not synchronized, or
* the key is invalid.
-------------------------------------------
Therefore my update task fails.

The named config of synology looks weird and I'm not deep enough into DNS, BIND9 and named to sort this out in due time.

**Comment by schmaun** [comment]
Hey,
thanks for your report but I have no time to take care about the adblocker.
Maybe the thread from the description helps you: https://forum.synology.com/enu/viewtopic.php?f=39&t=78126&p=310721#p310721
There is a V2 mentioned. Maybe that will solve your problem.
